/* ──────────────────────────────────────────────────────────────────────────
 * Toggle → backend opportunity type mapping (kept in sync with src/engine/
 * trading_engine.ts filter at the tick() level).
 *
 *   flashLoans     → ArbOpportunity.type === "arbitrage"
 *   yieldGaps      → ArbOpportunity.type === "yield"
 *   liquidations   → ArbOpportunity.type === "liquidation"
 *   chartPatterns  → ArbOpportunity.type === "chart_pattern"
 *   socialBuzz     → ArbOpportunity.type === "social_buzz"
 *   copyWhales     → ArbOpportunity.type === "copy_whale"
 *
 * NOTE: "mempool_pressure" has NO user toggle — it's always on. The signal
 * also feeds DecisionModel as the 5th AI weight (0.15 default).
 *
 * The "directional" type is generated by DecisionModel itself when aiScore
 * crosses the threshold and is not user-toggle-gated.
 * ────────────────────────────────────────────────────────────────────────── */

import { useState, useEffect } from "react";
import {
  Cpu, User, TrendingUp, MessageSquare, Eye, Brain,
  DollarSign, Clock, Zap, Shield, Lock, CheckCircle,
  ChevronRight, ChevronLeft, AlertTriangle, Layers
} from "lucide-react";
import { apiSaveConfig, apiGetConfig } from "../lib/api";
import VaultPanel from "../components/VaultPanel";
import WalletPanel from "../components/WalletPanel";

/* ─── Wizard ──────────────────────────────────────────────── */
function Wizard({ onDone }) {
  const [step, setStep] = useState(0);
  const [mode, setMode] = useState(null);
  const [cfg, setCfg] = useState({
    maxTrade: 1000, bigThreshold: 5000, requireBigApproval: true,
    from: "09:00", to: "16:00", pauseNews: false,
    flashLoans: true, yieldGaps: true, liquidations: false,
    chartPatterns: true, socialBuzz: false, copyWhales: false,
  });
  const set = (k, v) => setCfg(p => ({ ...p, [k]: v }));

  const steps = [
    { id: "mode" },
    ...(mode === "auto" ? [{ id: "limits" }, { id: "hours" }, { id: "deals" }] : []),
    { id: "done" },
  ];
  const cur = steps[step]?.id;
  const last = step === steps.length - 1;

  const canNext = cur === "mode" ? !!mode : true;

  return (
    <div style={{
      position: "fixed", inset: 0,
      background: "rgba(0,0,0,.8)", backdropFilter: "blur(12px)",
      zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center",
    }}>
      <div style={{
        background: "var(--bg2)", border: "1px solid var(--border2)",
        borderRadius: 28, width: 540, maxWidth: "95vw",
        maxHeight: "90vh", display: "flex", flexDirection: "column",
        animation: "fadeUp .3s ease", overflow: "hidden",
        boxShadow: "0 40px 80px rgba(0,0,0,.6)",
      }}>
        {/* Progress */}
        <div style={{ padding: "28px 36px 0", flexShrink: 0 }}>
          <div style={{ display: "flex", gap: 5, marginBottom: 24 }}>
            {steps.map((_, i) => (
              <div key={i} style={{
                flex: 1, height: 4, borderRadius: 4,
                background: i <= step
                  ? "linear-gradient(90deg,var(--v),var(--v2))"
                  : "var(--border2)",
                transition: "background .3s",
                boxShadow: i <= step ? "0 0 8px var(--v3)" : "none",
              }} />
            ))}
          </div>
        </div>

        {/* Body */}
        <div style={{ overflowY: "auto", padding: "0 36px 20px", flex: 1 }}>

          {/* Mode */}
          {cur === "mode" && (
            <>
              <div style={{ textAlign: "center", marginBottom: 28 }}>
                <div style={{
                  width: 56, height: 56, borderRadius: "50%",
                  background: "var(--v3)", border: "2px solid rgba(124,58,237,.3)",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  margin: "0 auto 14px",
                }}>
                  <Zap size={24} color="var(--v2)" />
                </div>
                <h2 style={{ fontSize: 20, fontWeight: 900, marginBottom: 8 }}>How do you want this to work?</h2>
                <p style={{ fontSize: 13, color: "var(--text2)", lineHeight: 1.65 }}>
                  Pick your style — you can change it anytime.
                </p>
              </div>

              <div className="mode-row">
                <button
                  className={`mode-btn ${mode === "auto" ? "sel-v" : ""}`}
                  onClick={() => setMode("auto")}
                >
                  <div className="mode-btn-icon">⚡</div>
                  <div className="mode-btn-title" style={{ color: mode === "auto" ? "var(--v2)" : "var(--text)" }}>
                    Trade for me
                  </div>
                  <div className="mode-btn-desc">
                    The system trades automatically within your limits. Check profits at your own pace.
                  </div>
                </button>

                <button
                  className={`mode-btn ${mode === "manual" ? "sel-c" : ""}`}
                  onClick={() => setMode("manual")}
                >
                  <div className="mode-btn-icon">👁️</div>
                  <div className="mode-btn-title" style={{ color: mode === "manual" ? "var(--cyan)" : "var(--text)" }}>
                    Ask me first
                  </div>
                  <div className="mode-btn-desc">
                    The system finds deals and pings you before doing anything. Full control, always.
                  </div>
                </button>
              </div>
            </>
          )}

          {/* Limits */}
          {cur === "limits" && (
            <>
              <h2 style={{ fontSize: 20, fontWeight: 900, marginBottom: 6 }}>How much can it spend per trade?</h2>
              <p style={{ fontSize: 13, color: "var(--text2)", marginBottom: 24, lineHeight: 1.65 }}>
                Hard limits the system will never exceed.
              </p>

              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                <div style={{ background: "var(--bg3)", borderRadius: 14, padding: "18px 20px" }}>
                  <label className="inp-label">Maximum per trade</label>
                  <div className="inp-hint">The most it can use in a single trade, ever.</div>
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 8 }}>
                    <span style={{ color: "var(--text3)" }}>$</span>
                    <input className="num-inp" type="number" value={cfg.maxTrade} min={10} step={100}
                      onChange={e => set("maxTrade", +e.target.value)}
                      style={{ marginTop: 0, marginBottom: 0 }} />
                  </div>
                </div>

                <div style={{ background: "var(--bg3)", borderRadius: 14, padding: "18px 20px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                    <div>
                      <label className="inp-label">Ask me before bigger trades</label>
                      <div className="inp-hint">Pause and wait for my approval above this amount.</div>
                      <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 8 }}>
                        <span style={{ color: "var(--text3)" }}>$</span>
                        <input className="num-inp" type="number" value={cfg.bigThreshold} min={100} step={500}
                          onChange={e => set("bigThreshold", +e.target.value)}
                          disabled={!cfg.requireBigApproval}
                          style={{ marginTop: 0, marginBottom: 0, opacity: cfg.requireBigApproval ? 1 : .4 }} />
                      </div>
                    </div>
                    <label className="sw" style={{ marginTop: 4 }}>
                      <input type="checkbox" checked={cfg.requireBigApproval} onChange={e => set("requireBigApproval", e.target.checked)} />
                      <div className="sw-track" />
                    </label>
                  </div>
                </div>
              </div>
            </>
          )}

          {/* Hours */}
          {cur === "hours" && (
            <>
              <h2 style={{ fontSize: 20, fontWeight: 900, marginBottom: 6 }}>When should it be active?</h2>
              <p style={{ fontSize: 13, color: "var(--text2)", marginBottom: 24, lineHeight: 1.65 }}>
                Restrict to certain hours, or leave the same time for 24/7 trading.
              </p>

              <div style={{ background: "var(--bg3)", borderRadius: 14, padding: "22px" }}>
                <div style={{ display: "flex", gap: 16, alignItems: "center", flexWrap: "wrap" }}>
                  <div>
                    <div style={{ fontSize: 10, color: "var(--text3)", fontWeight: 700, letterSpacing: ".8px", textTransform: "uppercase", marginBottom: 6 }}>From</div>
                    <input className="num-inp" type="time" value={cfg.from}
                      onChange={e => set("from", e.target.value)}
                      style={{ fontSize: 18, fontWeight: 800, width: 120, marginTop: 0, marginBottom: 0 }} />
                  </div>
                  <div style={{ fontSize: 20, color: "var(--text3)", marginTop: 16 }}>→</div>
                  <div>
                    <div style={{ fontSize: 10, color: "var(--text3)", fontWeight: 700, letterSpacing: ".8px", textTransform: "uppercase", marginBottom: 6 }}>To</div>
                    <input className="num-inp" type="time" value={cfg.to}
                      onChange={e => set("to", e.target.value)}
                      style={{ fontSize: 18, fontWeight: 800, width: 120, marginTop: 0, marginBottom: 0 }} />
                  </div>
                </div>
                <div style={{ fontSize: 11, color: "var(--text3)", marginTop: 14 }}>Uses your local timezone.</div>
              </div>

              <div className="toggle-row" style={{ marginTop: 12 }}
                onClick={() => set("pauseNews", !cfg.pauseNews)}>
                <div className="toggle-icon" style={{ background: "var(--gold2)" }}>
                  <AlertTriangle size={16} color="var(--gold)" />
                </div>
                <div>
                  <div className="toggle-main">Pause when big news drops</div>
                  <div className="toggle-desc">Stop automatically around major economic announcements that cause wild price swings.</div>
                </div>
                <label className="sw" onClick={e => e.stopPropagation()}>
                  <input type="checkbox" checked={cfg.pauseNews} onChange={e => set("pauseNews", e.target.checked)} />
                  <div className="sw-track" />
                </label>
              </div>
            </>
          )}

          {/* Deals */}
          {cur === "deals" && (
            <>
              <h2 style={{ fontSize: 20, fontWeight: 900, marginBottom: 6 }}>What types of deals can it take?</h2>
              <p style={{ fontSize: 13, color: "var(--text2)", marginBottom: 20, lineHeight: 1.65 }}>
                Toggle on the ones you want. You can change this anytime.
              </p>

              {[
                { k: "flashLoans",    icon: Zap,           color: "var(--v2)",   bg: "var(--v3)",    title: "Price gaps between exchanges", desc: "When the same coin is priced differently on two platforms — buy cheap, sell higher, in under a second." },
                { k: "yieldGaps",     icon: TrendingUp,    color: "var(--green)",bg: "var(--green2)",title: "Earn from idle coins",          desc: "Automatically move coins to wherever they earn the highest interest rate." },
                { k: "liquidations",  icon: DollarSign,    color: "var(--gold)", bg: "var(--gold2)", title: "Collect liquidation rewards",   desc: "Grab protocol payouts when leveraged positions fail — the platform pays you for it." },
              ].map(({ k, icon: Icon, color, bg, title, desc }) => (
                <div key={k} className={`toggle-row ${cfg[k] ? "active" : ""}`}
                  onClick={() => set(k, !cfg[k])}>
                  <div className="toggle-icon" style={{ background: bg }}>
                    <Icon size={16} color={color} />
                  </div>
                  <div style={{ flex: 1 }}>
                    <div className="toggle-main" style={{ color: cfg[k] ? color : "var(--text)" }}>{title}</div>
                    <div className="toggle-desc">{desc}</div>
                  </div>
                  <label className="sw" onClick={e => e.stopPropagation()}>
                    <input type="checkbox" checked={cfg[k]} onChange={e => set(k, e.target.checked)} />
                    <div className="sw-track" />
                  </label>
                </div>
              ))}

              {/* RWA greyed */}
              <div className="toggle-row disabled" style={{ marginTop: 4 }}>
                <div className="toggle-icon" style={{ background: "var(--border)" }}>
                  <Layers size={16} color="var(--text3)" />
                </div>
                <div style={{ flex: 1 }}>
                  <div className="toggle-main" style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    Real-World Asset trades <span className="cs-badge">Coming soon</span>
                  </div>
                  <div className="toggle-desc">Tokenized stocks, bonds and real assets. Crypto-only for now.</div>
                </div>
              </div>

              <div style={{ height: 1, background: "var(--border)", margin: "16px 0" }} />

              <div style={{ fontSize: 10, fontWeight: 800, textTransform: "uppercase", letterSpacing: ".8px", color: "var(--v2)", display: "flex", alignItems: "center", gap: 6, marginBottom: 10 }}>
                <Brain size={11} /> AI-driven trades
              </div>

              {[
                { k: "chartPatterns", icon: TrendingUp,   color: "var(--v2)",  bg: "var(--v3)",   title: "Chart pattern trades",    desc: "The AI reads price history and acts on reliable patterns — breakouts, momentum shifts.", badge: "72% success" },
                { k: "socialBuzz",    icon: MessageSquare,color: "var(--cyan)", bg: "var(--cyan2)",title: "Social buzz trades",       desc: "Catches trending coins early from Twitter and Telegram, exits before the hype fades.",    badge: "Trend detector" },
                { k: "copyWhales",    icon: Eye,           color: "var(--pink)",bg: "var(--pink2)",title: "Copy big investors",       desc: "Mirrors what the 500 largest crypto wallets are quietly buying.",                         badge: "Top 500 wallets" },
              ].map(({ k, icon: Icon, color, bg, title, desc, badge }) => (
                <div key={k} className={`toggle-row ${cfg[k] ? "active" : ""}`}
                  onClick={() => set(k, !cfg[k])}>
                  <div className="toggle-icon" style={{ background: bg }}>
                    <Icon size={16} color={color} />
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
                      <span className="toggle-main" style={{ color: cfg[k] ? color : "var(--text)" }}>{title}</span>
                      <span style={{ fontSize: 9, fontWeight: 800, padding: "1px 7px", borderRadius: 20, background: bg, color, border: `1px solid ${color}33` }}>{badge}</span>
                    </div>
                    <div className="toggle-desc">{desc}</div>
                  </div>
                  <label className="sw" onClick={e => e.stopPropagation()}>
                    <input type="checkbox" checked={cfg[k]} onChange={e => set(k, e.target.checked)} />
                    <div className="sw-track" />
                  </label>
                </div>
              ))}
            </>
          )}

          {/* Confirm */}
          {cur === "done" && (
            <div style={{ textAlign: "center", paddingTop: 8 }}>
              <div style={{
                width: 64, height: 64, borderRadius: "50%",
                background: "var(--green2)", border: "2px solid var(--green)",
                display: "flex", alignItems: "center", justifyContent: "center",
                margin: "0 auto 16px",
                boxShadow: "0 0 32px var(--green2)",
              }}>
                <CheckCircle size={28} color="var(--green)" />
              </div>
              <h2 style={{ fontSize: 22, fontWeight: 900, marginBottom: 8 }}>All set!</h2>
              <p style={{ fontSize: 13, color: "var(--text2)", marginBottom: 28, lineHeight: 1.65 }}>
                The system is configured and ready. You can tweak everything later from the My Setup page.
              </p>
              <div style={{ background: "var(--bg3)", borderRadius: 14, padding: "18px 20px", textAlign: "left" }}>
                <div style={{ fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: ".8px", color: "var(--text3)", marginBottom: 12 }}>Summary</div>
                {[
                  ["Mode",        mode === "auto" ? "Trades automatically" : "Asks before each trade"],
                  ["Max per trade", `$${cfg.maxTrade.toLocaleString()}`],
                  mode === "auto" && cfg.requireBigApproval && ["Ask me above", `$${cfg.bigThreshold.toLocaleString()}`],
                  ["Active hours",  `${cfg.from} → ${cfg.to}`],
                ].filter(Boolean).map(([label, value], i) => (
                  <div key={i} style={{ display: "flex", justifyContent: "space-between", fontSize: 13, marginBottom: 8 }}>
                    <span style={{ color: "var(--text2)" }}>{label}</span>
                    <span style={{ fontWeight: 700 }}>{value}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

        </div>

        {/* Footer nav */}
        <div style={{
          display: "flex", justifyContent: "space-between", gap: 10,
          padding: "16px 36px 28px", borderTop: "1px solid var(--border)", flexShrink: 0,
        }}>
          <button
            className="btn btn-ghost btn-sm"
            disabled={step === 0}
            onClick={() => setStep(s => s - 1)}
            style={{ opacity: step === 0 ? .3 : 1, cursor: step === 0 ? "default" : "pointer" }}
          >
            <ChevronLeft size={15} /> Back
          </button>
          <button
            className="btn btn-v btn-sm"
            disabled={!canNext}
            onClick={last ? () => onDone({ mode, cfg }) : () => setStep(s => s + 1)}
            style={{ opacity: canNext ? 1 : .3, cursor: canNext ? "pointer" : "default" }}
          >
            {last ? "Turn it on 🚀" : "Continue"} <ChevronRight size={15} />
          </button>
        </div>
      </div>
    </div>
  );
}

/* ─── Main BotBuilder page ────────────────────────────────── */
export default function BotBuilder({ userId }) {
  const [tradingMode, setTradingMode] = useState(null);
  const [showWizard, setShowWizard] = useState(false);
  const [savedCfg, setSavedCfg] = useState(null);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);

  const updateCfg = (key, value) => {
    setSavedCfg(prev => ({ ...prev, [key]: value }));
    setDirty(true);
  };

  const saveAll = async () => {
    if (!savedCfg || !userId) return;
    setSaving(true);
    try {
      await apiSaveConfig(userId, {
        mode: tradingMode === "auto" ? "active" : "viewer",
        maxTradeUsd: savedCfg.maxTrade,
        tradingHoursStart: savedCfg.from,
        tradingHoursEnd: savedCfg.to,
        flashLoans: savedCfg.flashLoans,
        yieldGaps: savedCfg.yieldGaps,
        liquidations: savedCfg.liquidations,
        chartPatterns: savedCfg.chartPatterns,
        socialBuzz: savedCfg.socialBuzz,
        copyWhales: savedCfg.copyWhales,
        dailyLimitUsd: savedCfg.dailyLossLimit,
      });
      localStorage.setItem("nx-cfg", JSON.stringify({ mode: tradingMode, cfg: savedCfg }));
      setDirty(false);
    } catch (err) {
      console.error("Failed to save config:", err);
      alert("Save failed: " + err.message);
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    // Try loading from backend first, fall back to localStorage
    if (userId) {
      apiGetConfig(userId)
        .then((data) => {
          if (data && data.mode) {
            setTradingMode(data.mode === "active" ? "auto" : "manual");
            setSavedCfg({
              ...(data.cfg || data),
              from: data.tradingHoursStart ?? (data.cfg?.from ?? "00:00"),
              to: data.tradingHoursEnd ?? (data.cfg?.to ?? "23:59"),
            });
          } else {
            // Nothing on backend, check localStorage
            const s = localStorage.getItem("nx-cfg");
            if (s) {
              const p = JSON.parse(s);
              setTradingMode(p.mode);
              setSavedCfg(p.cfg);
            } else {
              setShowWizard(true);
            }
          }
        })
        .catch(() => {
          const s = localStorage.getItem("nx-cfg");
          if (s) {
            const p = JSON.parse(s);
            setTradingMode(p.mode);
            setSavedCfg(p.cfg);
          } else {
            setShowWizard(true);
          }
        });
    } else {
      const s = localStorage.getItem("nx-cfg");
      if (s) {
        const p = JSON.parse(s);
        setTradingMode(p.mode);
        setSavedCfg(p.cfg);
      } else {
        setShowWizard(true);
      }
    }
  }, [userId]);

  function onDone({ mode, cfg }) {
    setTradingMode(mode); setSavedCfg(cfg); setShowWizard(false);
    localStorage.setItem("nx-cfg", JSON.stringify({ mode, cfg }));
    // Also save to backend
    if (userId) {
      apiSaveConfig(userId, {
        mode: mode === "auto" ? "active" : "viewer",
        maxTradeUsd: cfg.maxTrade,
        dailyLimitUsd: cfg.dailyLossLimit || 500,
        tradingHoursStart: cfg.from,
        tradingHoursEnd: cfg.to,
        flashLoans: cfg.flashLoans,
        yieldGaps: cfg.yieldGaps,
        liquidations: cfg.liquidations,
        chartPatterns: cfg.chartPatterns,
        socialBuzz: cfg.socialBuzz,
        copyWhales: cfg.copyWhales,
      }).catch((err) => console.error("Failed to save config to backend:", err));
    }
  }

  const OPPS = [
    { k: "flashLoans",    icon: Zap,            color: "var(--v2)",    bg: "var(--v3)",    title: "Price gaps between exchanges",  desc: "Buy cheap on one exchange, sell for more on another — under a second." },
    { k: "yieldGaps",     icon: TrendingUp,      color: "var(--green)", bg: "var(--green2)",title: "Earn from idle coins",           desc: "Rotate to the highest interest rate automatically." },
    { k: "liquidations",  icon: DollarSign,      color: "var(--gold)",  bg: "var(--gold2)", title: "Collect liquidation rewards",    desc: "Get paid by the protocol when others' positions fail." },
    { k: "chartPatterns", icon: Brain,            color: "var(--v2)",    bg: "var(--v4)",    title: "Chart pattern trades (AI)",      desc: "Trade when the AI spots a reliable price pattern.", badge: "72%" },
    { k: "socialBuzz",    icon: MessageSquare,    color: "var(--cyan)",  bg: "var(--cyan2)", title: "Social buzz trades (AI)",        desc: "Enter on viral hype, exit before it fades.", badge: "Trend" },
    { k: "copyWhales",    icon: Eye,              color: "var(--pink)",  bg: "var(--pink2)", title: "Copy big investors (AI)",        desc: "Mirror what the 500 largest wallets are buying.", badge: "Top 500" },
  ];

  const SAFETY = [
    { icon: Shield, color: "var(--green)", bg: "var(--green2)", title: "Scam token detector",         desc: "Automatically skips tokens that look like scams or rugs.", locked: true },
    { icon: Shield, color: "var(--green)", bg: "var(--green2)", title: "Fake liquidity scanner",       desc: "Detects artificially inflated pools before entering.", locked: true },
    { icon: Lock,   color: "var(--v2)",    bg: "var(--v3)",     title: "Private trade routing",        desc: "Trades sent via private channel so bots can't front-run you.", locked: true },
    { icon: AlertTriangle, color: "var(--gold)", bg: "var(--gold2)", title: "Pause when market goes crazy", desc: "Halts automatically if volatility spikes beyond normal.", locked: false },
  ];

  return (
    <div>
      {showWizard && <Wizard onDone={onDone} />}

      {/* Header */}
      <div className="sec-h" style={{ marginBottom: 24 }}>
        <div>
          <div className="sec-title">My Setup</div>
          <div className="sec-sub">Choose what the system is allowed to do for you.</div>
        </div>
        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
          {tradingMode && (
            <div style={{
              display: "flex", alignItems: "center", gap: 7,
              background: tradingMode === "auto" ? "var(--v3)" : "var(--cyan2)",
              border: `1px solid ${tradingMode === "auto" ? "rgba(124,58,237,.25)" : "rgba(0,212,255,.2)"}`,
              borderRadius: 100, padding: "5px 14px",
              fontSize: 12, fontWeight: 800,
              color: tradingMode === "auto" ? "var(--v2)" : "var(--cyan)",
            }}>
              {tradingMode === "auto" ? <Cpu size={12} /> : <User size={12} />}
              {tradingMode === "auto" ? "Auto-trading on" : "Approval mode on"}
            </div>
          )}
          <button className="btn btn-ghost btn-sm" onClick={() => setShowWizard(true)}>
            Reconfigure
          </button>
        </div>
      </div>

      <div className="setup-grid">
        {/* Wallet — balances + recent activity */}
        <WalletPanel />

        {/* Vault deposit/withdraw */}
        <VaultPanel userId={userId} />

        {/* Opportunities */}
        <div className="setup-card" style={{ gridColumn: "1 / -1" }}>
          <div className="setup-card-title">
            <Zap size={16} color="var(--v2)" /> What deals can it take?
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 8 }}>
            {OPPS.map(({ k, icon: Icon, color, bg, title, desc, badge }) => (
              <div key={k} className={`toggle-row ${savedCfg?.[k] ? "active" : ""}`}
                onClick={() => updateCfg(k, !savedCfg?.[k])}>
                <div className="toggle-icon" style={{ background: bg }}>
                  <Icon size={15} color={color} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
                    <span className="toggle-main" style={{ color: savedCfg?.[k] ? color : "var(--text)" }}>{title}</span>
                    {badge && <span style={{ fontSize: 9, fontWeight: 800, padding: "1px 6px", borderRadius: 20, background: bg, color, border: `1px solid ${color}33` }}>{badge}</span>}
                  </div>
                  <div className="toggle-desc">{desc}</div>
                </div>
                <label className="sw" onClick={e => e.stopPropagation()}>
                  <input type="checkbox" checked={!!savedCfg?.[k]} onChange={() => updateCfg(k, !savedCfg?.[k])} />
                  <div className="sw-track" />
                </label>
              </div>
            ))}
            {/* RWA coming soon */}
            <div className="toggle-row disabled">
              <div className="toggle-icon" style={{ background: "var(--border)" }}>
                <Layers size={15} color="var(--text3)" />
              </div>
              <div>
                <div className="toggle-main" style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--text3)" }}>
                  Real-World Asset trades <span className="cs-badge">Coming soon</span>
                </div>
                <div className="toggle-desc">Tokenized stocks, bonds, etc. — coming soon.</div>
              </div>
            </div>
          </div>
        </div>

        {/* Safety */}
        <div className="setup-card">
          <div className="setup-card-title">
            <Shield size={16} color="var(--green)" /> Safety & protection
          </div>
          {SAFETY.map(({ icon: Icon, color, bg, title, desc, locked }, i) => (
            <div key={i} className="toggle-row" style={{ opacity: locked ? 1 : 1 }}>
              <div className="toggle-icon" style={{ background: bg }}>
                <Icon size={15} color={color} />
              </div>
              <div style={{ flex: 1 }}>
                <div className="toggle-main">{title} {locked && <Lock size={10} color="var(--text3)" />}</div>
                <div className="toggle-desc">{desc}</div>
              </div>
              <label className="sw" onClick={e => e.stopPropagation()}>
                <input type="checkbox" defaultChecked disabled={locked} />
                <div className="sw-track" />
              </label>
            </div>
          ))}
        </div>

        {/* Hard limits */}
        <div className="setup-card">
          <div className="setup-card-title">
            <AlertTriangle size={16} color="var(--red)" /> Hard limits
            <span style={{ fontSize: 10, color: "var(--text3)", fontWeight: 500, marginLeft: 4 }}>— AI cannot override these</span>
          </div>

          <div style={{ marginBottom: 18 }}>
            <label className="inp-label">Max price change before cancelling trade (%)</label>
            <div className="inp-hint">Cancels automatically if price moves more than this before the trade goes through.</div>
            <input className="num-inp" type="number" value={savedCfg?.slippageMax ?? 0.5} step="0.1"
              onChange={e => updateCfg("slippageMax", +e.target.value)} />
          </div>

          <div>
            <label className="inp-label">Stop everything if daily losses hit ($)</label>
            <div className="inp-hint">The system shuts down completely for the rest of the day once this is reached.</div>
            <input className="num-inp" type="number" value={savedCfg?.dailyLossLimit ?? 500}
              onChange={e => updateCfg("dailyLossLimit", +e.target.value)} />
          </div>

          <button className="btn btn-v" style={{ width: "100%", borderRadius: 12, marginTop: 18, justifyContent: "center" }}
            onClick={saveAll} disabled={saving}>
            {saving ? "Saving..." : dirty ? "Save limits ●" : "Save limits"}
          </button>
        </div>

        {/* Active hours (if auto) */}
        {tradingMode === "auto" && savedCfg && (
          <div className="setup-card" style={{ gridColumn: "1 / -1" }}>
            <div className="setup-card-title">
              <Clock size={16} color="var(--cyan)" /> Active trading hours
            </div>
            <div style={{ display: "flex", gap: 16, alignItems: "center", marginBottom: 16 }}>
              <div>
                <div style={{ fontSize: 10, color: "var(--text3)", fontWeight: 700, letterSpacing: ".8px", textTransform: "uppercase", marginBottom: 6 }}>From</div>
                <input className="num-inp" type="time" value={savedCfg.from} style={{ width: 120, marginTop: 0, marginBottom: 0 }}
                  onChange={e => updateCfg("from", e.target.value)} />
              </div>
              <div style={{ fontSize: 18, color: "var(--text3)", marginTop: 14 }}>→</div>
              <div>
                <div style={{ fontSize: 10, color: "var(--text3)", fontWeight: 700, letterSpacing: ".8px", textTransform: "uppercase", marginBottom: 6 }}>To</div>
                <input className="num-inp" type="time" value={savedCfg.to} style={{ width: 120, marginTop: 0, marginBottom: 0 }}
                  onChange={e => updateCfg("to", e.target.value)} />
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 10, marginTop: 14 }}>
                <span style={{ fontSize: 11, color: "var(--text3)" }}>Same time = trade 24/7</span>
                {dirty && <button className="btn btn-v btn-sm" onClick={saveAll} disabled={saving}>
                  {saving ? "Saving..." : "Save"}
                </button>}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
